### ISSUE TITLE
Expects the database model to match the domain model

### ISSUE THREAD

**Issue by jumpalongjim** [jnicolau/NSpecifications#6]
Your implementation is nicely done, however it seems to require that the object type used in the data access code will match exactly with the type used in the domain model. This is not necessarily true, particularly when working with a _clean architecture_ approach.

One of the benefits you are seeking with _NSpecifications_ is for the domain model to be able to specify which documents it needs without any dependency on the database, but also to be able to apply the specification _in_ the database rather than only in memory. This means either that the database and domain need to be using the same object types, or else the repository that accepts the specification needs to do some additional complex mapping before sending the specification on to the database through a mapping object.

Is there any way to use _NSpecifications_ that bypasses this problem, i.e. avoids a dependency on the database from the application domain?

**Comment by jnicolau** [comment]
In order to decouple domain from data you just have to make sure that your DAL knows your Domain, but your Domain shouldn't know your DAL. This is how ORM works and has nothing to do with DDD. According to the ORM of your choice, your entities might use some attributes such as DataContracts but that isn't a dependency on your DAL. For example, if you use NHibernate you can have your mappings all done on your DAL with FluentMapping or XML configs. So now let's focus on the Repository, this is where it might get more tricky. Say that you have a UserRepository, you will have an IUserRepository in your Domain and you will have your UserRepository implementation in your DAL. So you want to do it in such a way that your DAL depends on your Domain (and not the other way around). Your Domain classes that need access to use some data persistence will get injected with the IUserRepository implementation from the DAL. Let me know if that helps.

**Comment by jnicolau** [comment]
By the way, your specifications have absolutely no dependency on the DAL, they only depende on the IEnumerable<T>.
