### ISSUE TITLE
Reusing ASpec for ternary models

### ISSUE THREAD

**Issue by ronnypmuliawan** [jnicolau/NSpecifications#8]
Hi,

I am currently exploring whether this library fits my project's requirement.

How would you suggest reusing the specification pattern on ternary models or related models? For example, I have Users, Businesses and BusinessUser ternary table.

If we already have this spec on User domain model,
`public static ASpec<User> Active => new Spec<User>(user => user.IsActive);`

How do I reuse the spec above for my BusinessUser ternary model?

Currently, below seems to be the only way to define the spec again.
`public static ASpec<BusinessUser> ActiveUser => new Spec<BusinessUser>(bizUser => bizUser.User.IsActive);`

**Comment by jnicolau** [comment]
In regards to DDD, usually ternary relationships are just a detail of Persistence. Does it make sense to have specs for a BusinessUser entity at the Domain level? Your spec could perfectly work only on the user directly. Let me know if you have some other use case that really needs BusinessUser.

**Comment by jnicolau** [comment]
Say that you have Business entity and you want to know all users that belong to that Business and are Active. If you are using an ORM such as EF you can easily get a property inside Business pointing to a collection of Users or vice-versa.
Your Business class has a BusinessId key and a method called GetActiveUsers().
GetActiveUsers will use a spec of User in order to query userRepository:
```
var activeUsersInBusiness = new Spec<User>(u => 
    u.Businesses.Any(b => b.BusinessId == this.BusinessId) && u.IsActive);
usersRepository.Find(activeUsersInBusiness);
```
Now you break this spec into 2, move them to the User class. and store them as static members.

**Comment by ronnypmuliawan** [comment]
Thanks for the suggestions @jnicolau. I'll try to define my spec in my aggregate root model, instead.

I was just playing with the library and realized that I could use projections (`Select` or `SelectMany`) to apply the ternary spec, if I really need to.

You should be able to close this issue.
